### ISSUE TITLE
Few questions and a thank you

### ISSUE THREAD

**Issue by DoubleF3lix** [isaiahr/bp5000#13]
Just wanted to say that this works absolutely flawlessly for my needs. My group wanted me to make a program from scratch, and even then I didn't think I was capable of doing the UI stuff, so this has saved me a lot of trouble. Thank you so much!

I was wondering what command you used to bundle this into an `.exe` however. Do you happen to have this on hand?

**Comment by isaiahr** [comment]
I think pyinstaller, not exactly sure how, its been a long time since I touched this project. glad you found it useful though!

**Comment by DoubleF3lix** [comment]
I've also found that I can run it manually by making a venv with 3.6 and calling `python gui.py`, so I guess I don't need to build it. Thank you so much anyways!

**Comment by DoubleF3lix** [comment]
I also found `gui.spec` is literally a file designed for PyInstaller lol
