### ISSUE TITLE
Editing bracket size / font

### ISSUE THREAD

**Issue by DoubleF3lix** [isaiahr/bp5000#14]
Just wondering if you can edit the size of the brackets so that the names can show up fully. Currently, any text longer than 11 characters gets cut off.

**Comment by isaiahr** [comment]
Hey @DoubleF3lix, 

I'm glad you found my project useful, and I appreciate your comments, however, I have moved on from working on it a long time ago and don't intend to spend any time working on it in the future. Unfortunately, this means that any things you want changed, added, or fixed, will have to done by someone else. I would be happy to point you in the right direction for this though!

I think for this the code to draw the brackets is in grf.py If i recall correctly. 

Sorry for the inconvenience.

**Comment by DoubleF3lix** [comment]
Oh okay, thank you!
